### ISSUE TITLE
Powershell Script Content and Sh File Contents Get Mixed Up Across Shared Machine Platforms

### ISSUE THREAD

**Issue by eliezerchavez** [dotnet/vscode-dotnet-runtime#159]
dotnet-install.sh: 7: Syntax error: newline unexpected

[DotNetAcquisition1610671763422.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/5817746/DotNetAcquisition1610671763422.txt)

**Comment by brandonh-msft** [comment]
New error now:

```shell
**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:25 char:3
+ if [ -t 1 ] && command -v tput > /dev/null; then
+   ~
Missing '(' after 'if' in if statement.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:25 char:5
+ if [ -t 1 ] && command -v tput > /dev/null; then
+     ~
Missing type name after '['.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:25 char:13
+ if [ -t 1 ] && command -v tput > /dev/null; then
+             ~~
The token '&&' is not a valid statement separator in this version.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:28 char:7
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+       ~
Missing '(' after 'if' in if statement.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:28 char:9
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+         ~
Missing type name after '['.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:28 char:26
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                          ~~
The token '&&' is not a valid statement separator in this version.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:28 char:30
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                              ~
Missing type name after '['.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:42 char:13
+ say_warning() {
+             ~
An expression was expected after '('.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:43 char:72
+ ... printf "%b\n" "${yellow:-}dotnet_install: Warning: $1${normal:-}" >&3
+                                                                        ~
Missing file specification after redirection operator.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:43 char:72
+ ... printf "%b\n" "${yellow:-}dotnet_install: Warning: $1${normal:-}" >&3
+                                                                        ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double 
quotation marks ("&") to pass it as part of a string.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement
 

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:25 char:3
+ if [ -t 1 ] && command -v tput > /dev/null; then
+   ~
Missing '(' after 'if' in if statement.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:25 char:5
+ if [ -t 1 ] && command -v tput > /dev/null; then
+     ~
Missing type name after '['.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:25 char:13
+ if [ -t 1 ] && command -v tput > /dev/null; then
+             ~~
The token '&&' is not a valid statement separator in this version.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:28 char:7
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+       ~
Missing '(' after 'if' in if statement.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:28 char:9
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+         ~
Missing type name after '['.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:28 char:26
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                          ~~
The token '&&' is not a valid statement separator in this version.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:28 char:30
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                              ~
Missing type name after '['.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:42 char:13
+ say_warning() {
+             ~
An expression was expected after '('.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:43 char:72
+ ... printf "%b\n" "${yellow:-}dotnet_install: Warning: $1${normal:-}" >&3
+                                                                        ~
Missing file specification after redirection operator.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1:43 char:72
+ ... printf "%b\n" "${yellow:-}dotnet_install: Warning: $1${normal:-}" >&3
+                                                                        ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double 
quotation marks ("&") to pass it as part of a string.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement
 

	at c:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\extension.js:2:13753
```

**Comment by cortex93** [comment]
I had the same error. Something weird happens. On my windows host, the content of the dist/install scripts/dotnet-install.ps1 was the sh one, and on the remote wsl, the dist/install scripts/dotnet-install.sh has the powershell content.

And looking at @brandonh-msft logs it seems it is the same things. You are on a win32 os but `C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.1.0\dist\install 
scripts\dotnet-install.ps1` contains the sh install script.

Removing both files fix the issue for me

**Comment by cortex93** [comment]
In fact, the issue still occurs after removing both files. It first install on windows host correctly but then, it fails in wsl with the powershell content. Remove the dotnet_install.ps1 on the host, and close the wsl connection. It will now fails on the host and the script contains linux content.

**Comment by leti367** [comment]
Any updates on this issue?

**Comment by sfoslund** [comment]
Thanks for pinging! I believe https://github.com/dotnet/vscode-dotnet-runtime/pull/284 should help here but I totally forgot to trigger a new release with this change included! Sorry about that, the new version should be available soon.

**Comment by sfoslund** [comment]
New versions have been released, please let me know if you continue seeing this error with version 1.3.0

**Comment by leti367** [comment]
That new release works. Thanks Sarah!

**Comment by sfoslund** [comment]
Awesome, closing this issue then.

**Comment by jmigual** [comment]
I can confirm that this issue is still there with version v1.5.0

I get the following output:
``` shell
Downloading the .NET Runtime.
Downloading .NET version(s) 6.0.2 ... Error!
Failed to download .NET 6.0.2:
Command failed: "/home/[username]/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/jmigual/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.2" -Version 6.0.2 -Runtime dotnet
/home/[username]/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected


 Error!
.NET Acquisition Failed: Installation failed: Error: Command failed: "/home/[username]/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/jmigual/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.2" -Version 6.0.2 -Runtime dotnet
/home/[username]/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected
```

**Comment by jacobcheatley** [comment]
Echoing @jmigual, I can also confirm I get this error on v1.5.0.

I am using remote SSH from a Windows 10 machine to another machine with the operating system Ubuntu 18.04. This may be the cause of the mix up.

```
Downloading the .NET Runtime.
Downloading .NET version(s) 6.0.1 ... Error!
Failed to download .NET 6.0.1:
Command failed: "/home/jacob/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/jacob/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.1" -Version 6.0.1 -Runtime dotnet
/home/jacob/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: 7: /home/jacob/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: Syntax error: newline unexpected


 Error!
.NET Acquisition Failed: Installation failed: Error: Command failed: "/home/jacob/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/jacob/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.1" -Version 6.0.1 -Runtime dotnet
/home/jacob/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: 7: /home/jacob/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: Syntax error: newline unexpected
```

The contents of dotnet-install.sh is very clearly a Powershell script as @ChampiYann suggests, hence the syntax error.

**Comment by ingo-desjardins** [comment]
Confirming that is still an issue.  Ubuntu 20.04 running in WSL 2.

Thank you @jacobcheatley for posting the workaround :

installing dotnet 6.0.2 manually (https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#install-the-runtime)

**Comment by mikeharder** [comment]
Also confirming this is still an issue.

@sfoslund: Can you please re-open this issue, or would you prefer I open a new issue?

**Comment by baronfel** [comment]
We can reopen this - it's definitely popped up again.

**Comment by mikeharder** [comment]
@baronfel: I am seeing the same issue as @jacobcheatley.  The content of `/home/user/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh` is a PowerShell script.

**Comment by baronfel** [comment]
Thanks for the confirmation. @joeloff is looking into getting a consistent repro.

**Comment by hansmbakker** [comment]
What happened for me:
- do not have `dotnetAcquisitionExtension.existingDotnetPath` in any settings.json
- Have a folder with some bicep files
- add a devcontainer setup based on the C# (.NET) configuration files in VS Code with these features:
  - git os-provided
  - azure-cli
  - powershell
- add these extensions to the devcontainer.json file:
  ```
  [
    "ms-dotnettools.csharp",
    "ms-azuretools.vscode-bicep",
    "ms-azure-devops.azure-pipelines",
    "ms-vscode.azurecli",
    "esbenp.prettier-vscode",
    "ms-vscode.powershell"
  ]
```
- build the devcontainer and open the container
- open a bicep file. The bicep extension will be triggered.
- apparently it fails to detect the `dotnet` command in the docker container even though it is based on `mcr.microsoft.com/vscode/devcontainers/dotnet:0-6.0-bullseye-slim`.
- It will try to acquire .NET, which fails like in https://github.com/dotnet/vscode-dotnet-runtime/issues/159#issuecomment-1035861424

Workaround for this situation, not a generic workaround:
in `devcontainer.json` in `customizations` --> `vscode`, add:
```json
			"settings": {
				"dotnetAcquisitionExtension.existingDotnetPath": [
					{
						"extensionId": "ms-azuretools.vscode-bicep",
						"path": "/usr/bin/dotnet"
					}
				]
			}
```

**Comment by nagilson** [comment]
We have a patch for this now and working on releasing it, major thanks to @sfoslund (who isn't on this team anymore, but still helped introduce me to how everything is setup) and @anthony-c-martin for finding a consistent repro and helping us test it, then finally confirming the patch should fix it. 😄

**Comment by mdemoret-nv** [comment]
@nagilson Any update on when the next release containing this fix will be pushed out? This has been a consistent pain point for us for the past 6 months. If there is any help I can provide with testing pre-releases, please let me know.

**Comment by nagilson** [comment]
@mdemoret-nv It should be fixed as of `v1.6.0`, which version are you on?

**Comment by mdemoret-nv** [comment]
I'm on `v1.6.0` but I was waiting for a `v1.6.1` release due to this line from the attached PR:

> We plan on releasing this as the 1.6.1 version.

Apologies, I must have gotten the issue mixed up and was waiting for the hotfix release since I am still seeing an error with `v1.6.0`:

![image](https://user-images.githubusercontent.com/42954918/232935773-9a6076e4-fb51-4f65-9fde-39af7a7aaf73.png)

With the log:
```
Downloading the .NET Runtime.
Downloading .NET version(s) 6.0.16 .......... Done!
.NET 6.0.16 executable path: /home/coder/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.16/dotnet
```

Any ideas on what issue I could have been thinking of?

**Comment by nagilson** [comment]
Ah, I see that there are some older duplicate issues to this one where I said 1.6.1. Sorry for that confusion.

I have not seen that issue occur. Are you developing your own extension and that extension has the error, or using an extension that relies on this extension? I will need to collect more information, is that all that comes out of clicking 'more info'? Please create a new issue and ping me @nagilson and I can take a look.
